### ISSUE TITLE
Struct tags for array of enum values

### ISSUE THREAD

**Issue by hrobertson** [swaggest/jsonschema-go#26]
I have a field that is an array of enum values.

The OpenAPI spec to represent this is this:

```json
"days": {
  "type": "array",
  "items": {
    "type": "string",
    "enum": [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    ]
  }
}
```
I can not find how this can be represented in a go struct tag. This does not work:
```go
Days []string `json:"days" enum:"Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday"`
```
It results in this incorrect (invalid?) OpenAPI schema:
```json
"days": {
  "enum": [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
  ],
  "type": "array",
  "items": {
    "type": "string",
  }
}
```

Thanks

**Comment by vearutop** [comment]
Field tags apply to the property for which they are defined, that's why you get `enum` for `days` and not for `days/items`.

In such case (slice of strings) you can not use field tags to define `enum`, but you can either create a named type and implement `Enum() []interface{}` on it, or define schema preparer and set up enum in it.

Please check this [example](https://github.com/swaggest/jsonschema-go/blob/v0.3.25/example_enum_test.go).

**Comment by hrobertson** [comment]
Thanks for the examples.
